name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install libsecp256k1
        run: git clone git@github.com:bitcoin-core/secp256k1 && cd secp256k1 && \
          ./autogen.sh && ./configure --enable-experimental --enable-module-{ecdh,recovery} && \
          make && sudo make install && cd ..

      - name: Install secp256k1-php
        run: git clone git@github.com:Bit-Wasp/secp256k1-php && cd secp256k1-php/secp256k1 && \
          phpize && ./configure --with-secp256k1 && \
          make && sudo make install && cd ..

      - name: Run test suite
        run: composer run-script test
        env:
          CASPER_PHP_SDK_TEST_NODE_URL: "136.243.187.84:7777"
